<option value="0" selected>Select Religion...</option>

<option value="181">Agnostic</option>
<option value="380">Ahmadi Muslim</option>
<option value="188">Anglican</option>
<option value="220">Apostolic</option>
<option value="460">Armenian Apostolic</option>
<option value="480">Armenian Orthodox</option>
<option value="182">Atheist</option>
<option value="1">Baha'i</option>
<option value="183">Baptist</option>
<option value="320">Bethel Apostolic</option>
<option value="402">Bible</option>
<option value="500">Born Again Christian</option>
<option value="2">Buddhist</option>
<option value="163">Catholic</option>
<option value="340">Catholique</option>
<option value="461">Chaldean Catholic</option>
<option value="3">Christian</option>
<option value="180">Christian Orthodox</option>
<option value="242">Church Of Christ</option>
<option value="260">Church Of England</option>
<option value="280">Church Of God</option>
<option value="4">Confucianism</option>
<option value="441">Coptic Orthodox</option>
<option value="401">Eastern Orthodox</option>
<option value="206">Evangelist</option>
<option value="187">Greek Orthodox</option>
<option value="207">Hebrew</option>
<option value="5">Hindu</option>
<option value="221">Hindu Jain</option>
<option value="205">Humanist</option>
<option value="6">Islam</option>
<option value="360">Islam - Sunni</option>
<option value="208">Ismaili Muslim</option>
<option value="420">Jain</option>
<option value="7">Jainism</option>
<option value="201">Jehovah's Witnesses</option>
<option value="160">Jewish</option>
<option value="8">Judaism</option>
<option value="209">Lutheran</option>
<option value="361">Maronite Catholic</option>
<option value="210">Mennonite</option>
<option value="211">Methodist</option>
<option value="202">Mormon</option>
<option value="185">Muslim</option>
<option value="440">Non Denominational</option>
<option value="9997">Not Provided</option>
<option value="186">Orthodox</option>
<option value="190">Pentecostal</option>
<option value="203">Presbyterian</option>
<option value="161">Protestant</option>
<option value="212">Quaker</option>
<option value="162">Roman Catholic</option>
<option value="214">Russian Orthodox</option>
<option value="300">Salvation Army</option>
<option value="222">Scientology</option>
<option value="213">Serbian Orthodox</option>
<option value="100">Seventh Day Adventist</option>
<option value="9">Shinto</option>
<option value="10">Sikh</option>
<option value="204">Spiritualism</option>
<option value="11">Taoism</option>
<option value="240">Ukrainian Catholic</option>
<option value="400">Ukrainian Orthodox</option>
<option value="215">Unitarian</option>
<option value="200">United Church</option>
<option value="241">Wesleyan</option>
<option value="184">Wiccan</option>
<option value="12">Zoroastrianism</option>
