<option value="0" selected>Select Religion...</option>
<option value="Agnostic">Agnostic</option>
<option value="Ahmadi Muslim">Ahmadi Muslim</option>
<option value="Anglican">Anglican</option>
<option value="Apostolic">Apostolic</option>
<option value="Armenian Apostolic">Armenian Apostolic</option>
<option value="Armenian Orthodox">Armenian Orthodox</option>
<option value="Atheist">Atheist</option>
<option value="Baha'i">Baha'i</option>
<option value="Baptist">Baptist</option>
<option value="Bethel Apostolic">Bethel Apostolic</option>
<option value="Bible">Bible</option>
<option value="Born Again Christian">Born Again Christian</option>
<option value="Buddhist">Buddhist</option>
<option value="Catholic">Catholic</option>
<option value="Catholique">Catholique</option>
<option value="Chaldean Catholic">Chaldean Catholic</option>
<option value="Christian">Christian</option>
<option value="Christian Orthodox">Christian Orthodox</option>
<option value="Church Of Christ">Church Of Christ</option>
<option value="Church Of England">Church Of England</option>
<option value="Church Of God">Church Of God</option>
<option value="Confucianism">Confucianism</option>
<option value="Coptic Orthodox">Coptic Orthodox</option>
<option value="Eastern Orthodox">Eastern Orthodox</option>
<option value="Evangelist">Evangelist</option>
<option value="Greek Orthodox">Greek Orthodox</option>
<option value="Hebrew">Hebrew</option>
<option value="Hindu">Hindu</option>
<option value="Hindu Jain">Hindu Jain</option>
<option value="Humanist">Humanist</option>
<option value="Islam">Islam</option>
<option value="Islam - Sunni">Islam - Sunni</option>
<option value="Ismaili Muslim">Ismaili Muslim</option>
<option value="Jain">Jain</option>
<option value="Jainism">Jainism</option>
<option value="Jehovah's Witnesses">Jehovah's Witnesses</option>
<option value="Jewish">Jewish</option>
<option value="Judaism">Judaism</option>
<option value="Lutheran">Lutheran</option>
<option value="Maronite Catholic">Maronite Catholic</option>
<option value="Mennonite">Mennonite</option>
<option value="Methodist">Methodist</option>
<option value="Mormon">Mormon</option>
<option value="Muslim">Muslim</option>
<option value="Non Denominational">Non Denominational</option>
<option value="Not Provided">Not Provided</option>
<option value="Orthodox">Orthodox</option>
<option value="Pentecostal">Pentecostal</option>
<option value="Presbyterian">Presbyterian</option>
<option value="Protestant">Protestant</option>
<option value="Quaker">Quaker</option>
<option value="Roman Catholic">Roman Catholic</option>
<option value="Russian Orthodox">Russian Orthodox</option>
<option value="Salvation Army">Salvation Army</option>
<option value="Scientology">Scientology</option>
<option value="Serbian Orthodox">Serbian Orthodox</option>
<option value="Seventh Day Adventist">Seventh Day Adventist</option>
<option value="Shinto">Shinto</option>
<option value="Sikh">Sikh</option>
<option value="Spiritualism">Spiritualism</option>
<option value="Taoism">Taoism</option>
<option value="Ukrainian Catholic">Ukrainian Catholic</option>
<option value="Ukrainian Orthodox">Ukrainian Orthodox</option>
<option value="Unitarian">Unitarian</option>
<option value="United Church">United Church</option>
<option value="Wesleyan">Wesleyan</option>
<option value="Wiccan">Wiccan</option>
<option value="Zoroastrianism">Zoroastrianism</option>
